name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - "master"

env:
  PROJECT_ID: trim-keep-440008-a8 # Google Cloud project ID
  REGION: us-central1 # Google Cloud region
  SERVICE_NAME: rotter # Cloud Run service name
  ACTION_GCP_CREDENTIALS: ${{ secrets.ACTION_GCP_CREDENTIALS }} # GCP service account credentials

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.ACTION_GCP_CREDENTIALS }}
          
      - name: Configure Docker authentication
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |
          IMAGE=gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA
          docker build --tag $IMAGE \
            --build-arg NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }} \
            --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }} .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          IMAGE=gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image $IMAGE \
            --allow-unauthenticated \
            --region ${{ env.REGION }}
